import { defineConfig, loadEnv } from 'vite';
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import react from '@vitejs/plugin-react';

// Dev-server routes for the App Store, which in a deployment are Caddy's and
// the oauth2-proxy's job (see APP-STORE.md).
//
// The App Store backend only accepts a real Keycloak access token, so there are
// two useful setups: with a local oauth2-proxy (APP_STORE_BFF_UPSTREAM and
// AUTH_PROXY_UPSTREAM pointing at it), the proxy receives the full path and
// injects the bearer; without one, /api/app-store goes straight to FastAPI with
// the prefix stripped — the page renders, the API answers 401.
function appStoreProxy(env) {
  const proxy = {};
  if (env.AUTH_PROXY_UPSTREAM) {
    proxy['/oauth2'] = { target: env.AUTH_PROXY_UPSTREAM, changeOrigin: true };
  }
  if (env.APP_STORE_BFF_UPSTREAM) {
    proxy['/api/app-store'] = { target: env.APP_STORE_BFF_UPSTREAM, changeOrigin: true };
  } else {
    proxy['/api/app-store'] = {
      target: env.APP_STORE_UPSTREAM || 'http://localhost:8000',
      changeOrigin: true,
      rewrite: p => p.replace(/^\/api\/app-store/, ''),
    };
  }
  return proxy;
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const cfgPath = path.resolve(import.meta.dirname, 'web/config.js');

  // During development, generate the config.js file dynamically
  // This allows us to use .env variables without hardcoding them.
  //
  // Built as an object and serialised with JSON.stringify rather than
  // interpolated into a template string: a value containing a quote used to
  // produce a syntactically broken config.js (and an unset variable the literal
  // string "undefined"), which fails at load time as a blank page rather than
  // as a readable error. The equivalent heredoc in docker-entrypoint.sh has the
  // same shape; it stays as it is because escaping there would mean adding jq
  // to the runtime image for values that come from the Helm chart.
  if (mode === 'development') {
    const appconfig = {
      dynamicZonesBaseUrl: env.DYNAMIC_ZONE_BASE_URL || '',
      cloudResourcesBaseUrl: env.CLOUD_RESOURCES_BASE_URL || '',
      cloudResourcesMcpUrl: env.CLOUD_RESOURCES_MCP_URL || '',
      dynamicZonesMcpUrl: env.DYNAMIC_ZONE_MCP_URL || '',
      appStoreBaseUrl: env.APP_STORE_BASE_URL || '/api/app-store',
      appStoreFrontendUrl: env.APP_STORE_FRONTEND_URL || 'http://localhost:5173',
      appStoreEnabled: env.APP_STORE_ENABLED !== 'false',
      acmeServer: env.ACME_SERVER || 'https://certificates.dhbw.cloud',
      dummyAuth: env.DUMMY_AUTH === 'true',
      oidc: {
        client_id: env.OIDC_CLIENT_ID || '',
        issuer_url: env.OIDC_ISSUER_URL || '',
        end_session_url: env.OIDC_END_SESSION_URL || '',
      },
    };
    mkdirSync(path.dirname(cfgPath), { recursive: true });
    writeFileSync(cfgPath,
      `// Auto-generated by Vite during build (mode: ${mode}) — do not edit.\n` +
      `window.appconfig = ${JSON.stringify(appconfig, null, 2)};\n`);
  }

  return {
    root: 'web',
    // Source files are .jsx, handled natively by @vitejs/plugin-react
    // (automatic JSX runtime + React Fast Refresh in dev).
    plugins: [react()],
    build: {
      outDir: '../dist',
      emptyOutDir: true,
      rollupOptions: {
        output: {
          // Split large vendors into their own long-lived cacheable chunks
          // (swagger-ui is dynamically imported, so it already lands in its own
          // async chunk and is intentionally not listed here). vite 8 / rolldown
          // requires manualChunks to be a function, not the object map.
          manualChunks(id) {
            if (id.includes('/node_modules/@mantine/')) return 'mantine';
            if (/\/node_modules\/(react|react-dom|wouter)\//.test(id)) return 'vendor';
          },
        },
      },
    },
    server: {
      port: 8084,
      proxy: appStoreProxy(env),
    },
    // Unit tests. Two kinds, and the default stays the cheap one.
    //
    // *.test.js are the pure functions — the arithmetic and the string rules
    // that are wrong silently. They run in `node`, with no DOM.
    //
    // *.test.jsx are the render smoke tests, and they opt into jsdom per file
    // with a `@vitest-environment` docblock so the pure tests keep running in
    // milliseconds. They exist because two releases in one day shipped views
    // that could not render at all: once a free variable ESLint would have
    // caught, once an infinite render loop nothing here could see — lint green,
    // tests green, build green, page blank.
    // Paths are relative to `root` above, i.e. web/.
    test: {
      environment: 'node',
      include: ['**/*.test.js', '**/*.test.jsx'],
    },
    define: {
      __APP_VERSION__: JSON.stringify(process.env.npm_package_version),
    },
    clearScreen: true
  };
});
